export const BEVERAGE_TYPES = {
    COLA: "cola",
    ORANGE: "orange",
    LEMON: "lemon",
    WATER: "water",
    MINERAL: "mineral",
    SPORT: "sport",
    ENERGY: "energy",
    CUSTOM: "custom",
};

export const BEVERAGE_CATALOG = {
    [BEVERAGE_TYPES.COLA]: {
        id: BEVERAGE_TYPES.COLA,
        label: "Cola clásica",
        shortLabel: "Cola",
        labelText: "KICK COLA",
        subLabel: "Classic 2026",
        footerText: "Edición académica",
        liquidColor: "#2a1208",
        liquidOpacity: 0.88,
        bottleTint: "#f1e4d6",
        bottleOpacity: 0.5,
        capColor: "#1f1510",
        labelBackground: "#18110d",
        labelTextColor: "#fff7e8",
        labelAccent: "#d6b45c",
        secondaryAccent: "#b92d2d",
        pattern: "premium",
        bubbles: true,
        bubbleCount: 34,
        condensation: false,
        carbonationSpeed: 1.35,
        highlightIntensity: 0.38,
        bottleShape: "classic",
        materialMode: "plastic-dark",
        description: "Bebida tipo cola para una presentación premium y elegante.",
    },

    [BEVERAGE_TYPES.ORANGE]: {
        id: BEVERAGE_TYPES.ORANGE,
        label: "Naranja",
        shortLabel: "Naranja",
        labelText: "KICK ORANGE",
        subLabel: "Fresh 2026",
        footerText: "Sabor cítrico",
        liquidColor: "#f47b20",
        liquidOpacity: 0.78,
        bottleTint: "#fff1dd",
        bottleOpacity: 0.54,
        capColor: "#f47b20",
        labelBackground: "#fff4e4",
        labelTextColor: "#431d0a",
        labelAccent: "#f47b20",
        secondaryAccent: "#f0c84b",
        pattern: "citrus",
        bubbles: true,
        bubbleCount: 26,
        condensation: false,
        carbonationSpeed: 1.15,
        highlightIntensity: 0.34,
        bottleShape: "classic",
        materialMode: "plastic-clear",
        description: "Bebida de naranja para una caja juvenil y llamativa.",
    },

    [BEVERAGE_TYPES.LEMON]: {
        id: BEVERAGE_TYPES.LEMON,
        label: "Lima limón",
        shortLabel: "Lima limón",
        labelText: "KICK LEMON",
        subLabel: "Lime 2026",
        footerText: "Refrescante",
        liquidColor: "#b7ef77",
        liquidOpacity: 0.62,
        bottleTint: "#f6fff0",
        bottleOpacity: 0.48,
        capColor: "#2f7d55",
        labelBackground: "#f7fff2",
        labelTextColor: "#183624",
        labelAccent: "#2f7d55",
        secondaryAccent: "#c8ef72",
        pattern: "fresh",
        bubbles: true,
        bubbleCount: 28,
        condensation: false,
        carbonationSpeed: 1.25,
        highlightIntensity: 0.36,
        bottleShape: "classic",
        materialMode: "plastic-clear",
        description: "Bebida lima-limón con estilo fresco y deportivo.",
    },

    [BEVERAGE_TYPES.WATER]: {
        id: BEVERAGE_TYPES.WATER,
        label: "Agua natural",
        shortLabel: "Agua",
        labelText: "PURE WATER",
        subLabel: "Natural",
        footerText: "Hidratación",
        liquidColor: "#d8f2ff",
        liquidOpacity: 0.34,
        bottleTint: "#eaf8ff",
        bottleOpacity: 0.38,
        capColor: "#ffffff",
        labelBackground: "#eef9ff",
        labelTextColor: "#0d3b5c",
        labelAccent: "#2f86c7",
        secondaryAccent: "#7fd3ff",
        pattern: "water",
        bubbles: false,
        bubbleCount: 0,
        condensation: true,
        dropletCount: 42,
        carbonationSpeed: 0.45,
        highlightIntensity: 0.42,
        bottleShape: "water",
        materialMode: "plastic-clear",
        description: "Agua natural para una presentación limpia e institucional.",
    },

    [BEVERAGE_TYPES.MINERAL]: {
        id: BEVERAGE_TYPES.MINERAL,
        label: "Agua mineral",
        shortLabel: "Mineral",
        labelText: "MINERAL BLUE",
        subLabel: "Sparkling",
        footerText: "Agua con gas",
        liquidColor: "#cfefff",
        liquidOpacity: 0.42,
        bottleTint: "#e9f8ff",
        bottleOpacity: 0.42,
        capColor: "#c6d7e6",
        labelBackground: "#f6fbff",
        labelTextColor: "#17384f",
        labelAccent: "#7aa7c7",
        secondaryAccent: "#d6d6d6",
        pattern: "mineral",
        bubbles: true,
        bubbleCount: 36,
        condensation: true,
        dropletCount: 30,
        carbonationSpeed: 0.8,
        highlightIntensity: 0.44,
        bottleShape: "water",
        materialMode: "plastic-clear",
        description: "Agua mineral con burbujas finas y estilo más premium.",
    },

    [BEVERAGE_TYPES.SPORT]: {
        id: BEVERAGE_TYPES.SPORT,
        label: "Agua deportiva",
        shortLabel: "Sport",
        labelText: "SPORT AQUA",
        subLabel: "Active 2026",
        footerText: "Mundial Edition",
        liquidColor: "#a7e7ff",
        liquidOpacity: 0.46,
        bottleTint: "#e8fbff",
        bottleOpacity: 0.44,
        capColor: "#1f91d1",
        labelBackground: "#061d2e",
        labelTextColor: "#ffffff",
        labelAccent: "#1f91d1",
        secondaryAccent: "#2f7d55",
        pattern: "sport",
        bubbles: false,
        bubbleCount: 0,
        condensation: true,
        dropletCount: 34,
        carbonationSpeed: 0.55,
        highlightIntensity: 0.5,
        bottleShape: "sport",
        materialMode: "plastic-clear",
        description: "Agua deportiva con estética de evento futbolístico.",
    },

    [BEVERAGE_TYPES.ENERGY]: {
        id: BEVERAGE_TYPES.ENERGY,
        label: "Energizante",
        shortLabel: "Energizante",
        labelText: "ENERGY BYTE",
        subLabel: "Tech Boost",
        footerText: "Edición tecnológica",
        liquidColor: "#e2ff3f",
        liquidOpacity: 0.58,
        bottleTint: "#d8d8d8",
        bottleOpacity: 0.34,
        capColor: "#111111",
        labelBackground: "#111111",
        labelTextColor: "#e2ff3f",
        labelAccent: "#e2ff3f",
        secondaryAccent: "#1f91d1",
        pattern: "energy",
        bubbles: true,
        bubbleCount: 18,
        condensation: false,
        carbonationSpeed: 1.6,
        highlightIntensity: 0.56,
        bottleShape: "slim",
        materialMode: "metallic",
        description: "Bebida energética con estilo tecnológico y juvenil.",
    },

    [BEVERAGE_TYPES.CUSTOM]: {
        id: BEVERAGE_TYPES.CUSTOM,
        label: "Bebida personalizada",
        shortLabel: "Personalizada",
        labelText: "KICKOFF DRINK",
        subLabel: "Custom",
        footerText: "Tu diseño",
        liquidColor: "#2f86c7",
        liquidOpacity: 0.68,
        bottleTint: "#f2eee7",
        bottleOpacity: 0.5,
        capColor: "#f4f1e8",
        labelBackground: "#fff7e8",
        labelTextColor: "#2b2118",
        labelAccent: "#c59a4a",
        secondaryAccent: "#b92d2d",
        pattern: "custom",
        bubbles: true,
        bubbleCount: 20,
        condensation: false,
        dropletCount: 0,
        carbonationSpeed: 1,
        highlightIntensity: 0.36,
        bottleShape: "classic",
        materialMode: "plastic-clear",
        description: "Bebida editable para adaptar colores y textos al pedido.",
    },
};

export function getBeverage(type = BEVERAGE_TYPES.CUSTOM) {
    return BEVERAGE_CATALOG[type] ?? BEVERAGE_CATALOG[BEVERAGE_TYPES.CUSTOM];
}

export function getBeverageOptions() {
    return Object.values(BEVERAGE_CATALOG).map((beverage) => ({
        id: beverage.id,
        label: beverage.label,
        shortLabel: beverage.shortLabel,
        description: beverage.description,
    }));
}